### ISSUE TITLE
Inconsistent formats

### ISSUE THREAD

**Issue by mortonjt** [tymor22/tm-vec#14]
There are quite a few different file formats floating around 

For instance, I have the 4 files
```
 wget https://users.flatironinstitute.org/thamamsy/public_www/embeddings_cath_s100_final.npy                                                                                                            
 wget https://users.flatironinstitute.org/thamamsy/public_www/embeddings_cath_s100_w_metadata.tsv                                                                                                       
 wget https://users.flatironinstitute.org/thamamsy/public_www/cath_large.npy                                                                                                                            
 wget https://users.flatironinstitute.org/thamamsy/public_www/cath_large_metadata.npy  
```

I'm not sure what the difference is, but I'm guessing that the 2 metadata files are sequence ids, but one is in tsv, the other is in npy.
And I'm assuming that these are both different subsets of CATH.  We need to document what each of these files are, and standardize the formats (i.e. either make everything tsv or npy).

**Comment by tymor22** [comment]
Ignore the cath_s100 files here - CATH large is the entirety of CATH
