### ISSUE TITLE
Issues on Embed sequences with TM-vec.

### ISSUE THREAD

**Issue by maovshao** [tymor22/tm-vec#26]
Hi researchers, thanks for sharing such awesome work.
But when I run TM-VEC locally, I encounter the following problems.
- For `ipynb/repo_EMBED.ipynb`
```bash
#Load the ProtTrans model and ProtTrans tokenizer
tokenizer = T5Tokenizer.from_pretrained("Rostlab/prot_t5_xl_uniref50", do_lower_case=False )
model = T5EncoderModel.from_pretrained("Rostlab/prot_t5_xl_uniref50")
```

**_Error:_**
OSError: Can't load tokenizer for 'Rostlab/prot_t5_xl_uniref50'. If you were trying to load it from https://huggingface.co/models, make sure you don't have a local directory with the same name. Otherwise, make sure 'Rostlab/prot_t5_xl_uniref50' is the correct path to a directory containing all relevant files for a T5Tokenizer tokenizer.

**_Solution:_**
I finally solved the problem by downloading `prot_t5_xl_uniref50` locally instead of using the URL to download. But I guess it may be due to the version of `Transformers`, because in https://huggingface.co/Rostlab/prot_t5_xl_uniref50/tree/main, the code used in `Use in Transformers` is as follows, different from code used in `ipynb/repo_EMBED.ipynb`.
```bash
# Load model directly
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
tokenizer = AutoTokenizer.from_pretrained("Rostlab/prot_t5_xl_uniref50")
model = AutoModelForSeq2SeqLM.from_pretrained("Rostlab/prot_t5_xl_uniref50")
```
- For https://github.com/flatironinstitute/deepblast/wiki/Searching-proteins
It says "Say that you have a file called my_proteins.fasta", but `my_proteins.fasta` is not used below. This may be a minor issue that may cause confusion for users.

Thanks for your response.

**Comment by mortonjt** [comment]
Hi @maovshao thank you for the notes!  Glad that you got this working.  Yes, we normally download `prot_t5_xl_uniref50` locally, since its 10 min download, and easier to reuse with a local copy.

Agreed, I think this would be great to include in the README.  Feel free to suggest edits via pull request -- otherwise we'll update with the comments in this thread later this week.

**Comment by maovshao** [comment]
Thanks for your quick reply.
I've suggested edits via pull request in https://github.com/tymor22/tm-vec/pull/27.
I hope this simple modification will make the work more user-friendly.

**Comment by mortonjt** [comment]
This should now be resolved with the updated README.  Thanks!
