### ISSUE TITLE
ImportError: libmkl_intel_lp64.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by nstrom1** [tymor22/tm-vec#28]
I am trying to run the example code to annotate bacteriocins and keep running into this ImportError when I run the following command.

```
tmvec-build-database \
>     --input-fasta bagel.fa \
>     --tm-vec-model tm_vec_cath_model.ckpt \
>     --tm-vec-config-path tm_vec_cath_model_params.json \
>     --device 'cpu' \
>     --output bagel_database
```

ImportError: libmkl_intel_lp64.so.1: cannot open shared object file: No such file or directory

**Comment by mortonjt** [comment]
Hi, did you try `conda install mkl=2021 mkl_fft ` as suggested in the readme?

**Comment by nstrom1** [comment]
@mortonjt Thanks, I think that solved this error.
