### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by gc26762524** [tymor22/tm-vec#34]
Dear Developers,

Following the tutorial, I got an error msg at the step of 

```
tmvec-build-database \
    --input-fasta bagel.fa \
    --tm-vec-model tm_vec_cath_model.ckpt \
    --tm-vec-config-path tm_vec_cath_model_params.json \
    --device 'gpu' \
    --output bagel_database
```

ImportError: libmkl_intel_lp64.so.1: cannot open shared object file: No such file or directory

I also tried to pip install mkl but still can't find  libmkl_intel_lp64.so.1. 

Could you please advise? Thank you. 

Also, I wonder are there are any other tutorials to follow. I feel that the current instruction from Github is not very easy for me to understand.

Cheng

**Comment by mortonjt** [comment]
Did you install mkl as specified in the install instructions?

**Comment by gc26762524** [comment]
Hi Jamie,

Thanks for your reply. I did conda install mkl=2021 mkl_fft as suggested in the instruction, and also tried some googling on mkl installation, but still failed to locate/use the libmkl_intel_lp64.so.1. Any thoughts?

Best,
Cheng

**Comment by mortonjt** [comment]
Hi, sometimes conda can act weird - I recommend creating a new environment
first and revisiting this if that doesn't work.

**Comment by ysy-scu** [comment]
Dear Author:
there are some thing wrong when I try to download models : wget https://users.flatironinstitute.org/thamamsy/public_www/tm_vec_cath_model.ckpt got a 503 error. Have you encountered this problem?
Eathon

**Comment by blackwer** [comment]
> Dear Author: there are some thing wrong when I try to download models : wget https://users.flatironinstitute.org/thamamsy/public_www/tm_vec_cath_model.ckpt got a 503 error. Have you encountered this problem? Eathon

Some of flatiron's web services are currently offline. They should be back up in the next few hours hopefully.

**Comment by mortonjt** [comment]
Hi the servers are temporarily down. Will be back up momentarily
