### ISSUE TITLE
Error report for downloading Database 

### ISSUE THREAD

**Issue by htma** [tymor22/tm-vec#42]
$ wget https://users.flatironinstitute.org/thamamsy/public_www/swiss_large.npy
--2024-09-25 09:45:27--  https://users.flatironinstitute.org/thamamsy/public_www/swiss_large.npy
Connecting to 127.0.0.1:7897... connected.
Proxy request sent, awaiting response... 301 Moved Permanently
Location: /~thamamsy/swiss_large.npy [following]
--2024-09-25 09:45:28--  https://users.flatironinstitute.org/~thamamsy/swiss_large.npy
Reusing existing connection to users.flatironinstitute.org:443.
Proxy request sent, awaiting response... 403 Forbidden
2024-09-25 09:45:28 ERROR 403: Forbidden.

Thanks !

**Comment by mortonjt** [comment]
Have you tried the zenodo link?

https://github.com/tymor22/tm-vec/issues/40

**Comment by htma** [comment]
sorry, I realy means to query a protein in swiss database embeddings. So I need your swiss embedding db and meta. 
Your zenodo link from paper only contains source code, not database files.

**Comment by htma** [comment]
Further more, #40 links to a cath-domain-seqs-S35-with-metadata file, not dabase embeddings.

**Comment by mortonjt** [comment]
Got it. Yes there is a different Zenodo link that has the Swiss database embeddings https://zenodo.org/records/11199459

**Comment by mortonjt** [comment]
I've updated the README to remove the broken links.  I'll close this, since it appears to be resolved, but feel free to follow up if there are additional outstanding issues.

**Comment by htma** [comment]
Thanks
